language: objective-c
osx_image: xcode7.3
xcode_project: TravisExample.xcodeproj
xcode_scheme: TravisExample
xcode_sdk: iphonesimulator9.2

script:
    - xcodebuild clean build -sdk iphonesimulator -scheme TravisExample
